name: CI
on: [pull_request]

env:
  PYTHON_VERSION: '3.9'
  VENV_DIR: ~/ci_venvs/tilelang_ci

jobs:
  format-check:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Ensure venv (local & persistent)
      run: |
        set -e
        REQS_HASH=$(cat requirements-test.txt 2>/dev/null || true)
        MARKER="${{ runner.temp }}/.venv_marker_${{ env.PYTHON_VERSION }}_${REQS_HASH:0:8}"

        if [[ -f "$MARKER" ]] && [[ -f "${{ env.VENV_DIR }}/bin/activate" ]]; then
          echo "venv exists and hash matches – reuse it"
        else
          echo "venv stale or missing – recreating"
          rm -rf "${{ env.VENV_DIR }}" "$MARKER"
          python -m venv "${{ env.VENV_DIR }}"
          # shellcheck source=/dev/null
          source "${{ env.VENV_DIR }}/bin/activate"
          python -m pip install --upgrade pip
          [[ -f requirements-test.txt ]] && \
            PIP_NO_BUILD_ISOLATION=1 pip install -r requirements-test.txt
          pip install .
          touch "$MARKER"
        fi

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Run format check
      run: |
        source "${{ env.VENV_DIR }}/bin/activate"
        ./format.sh

  build-test:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Ensure venv (local & persistent)
      run: |
        set -e
        REQS_HASH=$(cat requirements-test.txt 2>/dev/null || true)
        MARKER="${{ runner.temp }}/.venv_marker_${{ env.PYTHON_VERSION }}_${REQS_HASH:0:8}"

        if [[ -f "$MARKER" ]] && [[ -f "${{ env.VENV_DIR }}/bin/activate" ]]; then
          echo "venv exists and hash matches – reuse it"
        else
          echo "venv stale or missing – recreating"
          rm -rf "${{ env.VENV_DIR }}" "$MARKER"
          python -m venv "${{ env.VENV_DIR }}"
          source "${{ env.VENV_DIR }}/bin/activate"
          python -m pip install --upgrade pip
          [[ -f requirements-test.txt ]] && \
            PIP_NO_BUILD_ISOLATION=1 pip install -r requirements-test.txt
          pip install .
          touch "$MARKER"
        fi

    - name: Install project (wheel form)
      run: |
        source "${{ env.VENV_DIR }}/bin/activate"
        pip install .

    - name: Run examples
      run: |
        source "${{ env.VENV_DIR }}/bin/activate"
        cd examples
        unset PYTHONPATH
        python -m pytest -n 4 **/test*.py

    - name: Run tests
      run: |
        source "${{ env.VENV_DIR }}/bin/activate"
        cd testing/python
        unset PYTHONPATH
        python -m pytest -n 4